<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class HsformsAPI {
	private $hsforms_api_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'hsforms_api_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'hsforms_api_page_init' ) );
	}

	public function hsforms_api_add_plugin_page() {
		add_submenu_page(
			'hsforms-options',
			__( 'Hotelsuite API', 'tps' ),
			__( 'Hotelsuite API', 'tps' ),
			'manage_options',
            'hsforms-api',
            array( $this, 'hsforms_api_create_admin_page' ) // function
		);
	}

	public function hsforms_api_create_admin_page() {
		$this->hsforms_api_options = get_option( 'hsforms_api_option_name' ); ?>

		<div class="wrap">
			<h2>Hsforms API</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'hsforms_api_option_group' );
					do_settings_sections( 'hsforms-api-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function hsforms_api_page_init() {
		register_setting(
			'hsforms_api_option_group', // option_group
			'hsforms_api_option_name', // option_name
			array( $this, 'hsforms_api_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'hsforms_api_setting_section', // id
			'Settings', // title
			array( $this, 'hsforms_api_section_info' ), // callback
			'hsforms-api-admin' // page
		);

		add_settings_field(
			'enable_api', // id
			'Enable API', // title
			array( $this, 'hsforms_enable_api_callback' ), // callback
			'hsforms-api-admin', // page
			'hsforms_api_setting_section' // section
		);

		add_settings_field(
			'api_url', // id
			'API URL', // title
			array( $this, 'hsforms_api_url_callback' ), // callback
			'hsforms-api-admin', // page
			'hsforms_api_setting_section' // section
		);

		add_settings_field(
			'client_id', // id
			'API USER (client_id)', // title
			array( $this, 'hsforms_client_id_callback' ), // callback
			'hsforms-api-admin', // page
			'hsforms_api_setting_section' // section
		);

		add_settings_field(
			'client_secret', // id
			'API PASSWORD (client_secret)', // title
			array( $this, 'hsforms_client_secret_callback' ), // callback
			'hsforms-api-admin', // page
			'hsforms_api_setting_section' // section
		);

		add_settings_field(
			's8_key', // id
			'Suite8 key (if any)', // title
			array( $this, 'hsforms_s8_key_callback' ), // callback
			'hsforms-api-admin', // page
			'hsforms_api_setting_section' // section
		);
	}

	public function hsforms_api_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['enable_api'] ) ) {
			$sanitary_values['enable_api'] = $input['enable_api'];
		}

		if ( isset( $input['api_url'] ) ) {
			$sanitary_values['api_url'] = sanitize_text_field( $input['api_url'] );
		}

		if ( isset( $input['client_id'] ) ) {
			$sanitary_values['client_id'] = sanitize_text_field( $input['client_id'] );
		}

		if ( isset( $input['client_secret'] ) ) {
			$sanitary_values['client_secret'] = sanitize_text_field( $input['client_secret'] );
		}

		if ( isset( $input['s8_key'] ) ) {
			$sanitary_values['s8_key'] = sanitize_text_field( $input['s8_key'] );
		}

		return $sanitary_values;
	}

	public function hsforms_api_section_info() {
		
	}

	public function hsforms_enable_api_callback() {
		printf(
			'<input type="checkbox" name="hsforms_api_option_name[enable_api]" id="enable_api" value="enable_api" %s>',
			( isset( $this->hsforms_api_options['enable_api'] ) && $this->hsforms_api_options['enable_api'] === 'enable_api' ) ? 'checked' : ''
		);
	}

	public function hsforms_api_url_callback() {
		printf(
			'<input class="regular-text" type="text" name="hsforms_api_option_name[api_url]" id="api_url" value="%s">',
			isset( $this->hsforms_api_options['api_url'] ) ? esc_attr( $this->hsforms_api_options['api_url']) : ''
		);
	}

	public function hsforms_client_id_callback() {
		printf(
			'<input class="regular-text" type="text" name="hsforms_api_option_name[client_id]" id="client_id" value="%s">',
			isset( $this->hsforms_api_options['client_id'] ) ? esc_attr( $this->hsforms_api_options['client_id']) : ''
		);
	}

	public function hsforms_client_secret_callback() {
		printf(
			'<input class="regular-text" type="text" name="hsforms_api_option_name[client_secret]" id="client_secret" value="%s">',
			isset( $this->hsforms_api_options['client_secret'] ) ? esc_attr( $this->hsforms_api_options['client_secret']) : ''
		);
	}

	public function hsforms_s8_key_callback() {
		printf(
			'<input class="regular-text" type="text" name="hsforms_api_option_name[s8_key]" id="s8_key" value="%s">',
			isset( $this->hsforms_api_options['s8_key'] ) ? esc_attr( $this->hsforms_api_options['s8_key']) : ''
		);
	}

}
if ( is_admin() )
	$hsforms_api = new HsformsAPI();

/* 
 * Retrieve this value with:
 * $hsforms_api_options = get_option( 'hsforms_api_option_name' ); // Array of All Options
 * $enable_api = $hsforms_api_options['enable_api']; // Enable API
 * $api_url = $hsforms_api_options['api_url']; // API URL
 * $client_id = $hsforms_api_options['client_id']; // API USER (client_id)
 * $client_secret = $hsforms_api_options['client_secret']; // API PASSWORD (client_secret)
 * $s8_key = $hsforms_api_options['s8_key']; // Suite8 key (if any)
 */
